export const channelList = [
    {
        "key":"affiliate4you",
        "label":"Affiliate4you",
        "country":"NL"
    },
    {
        "key":"wolterskluwer",
        "label":"WoltersKluwer",
        "country":"NL"
    },
    {
        "key":"custom_csv",
        "label":"Custom (CSV)",
        "country":"RS"
    },
    {
        "key":"sejourexpress",
        "label":"Sejour Express",
        "country":"FR"
    },
    {
        "key":"grosshandel",
        "label":"Grosshandel",
        "country":"DE"
    },
    {
        "key":"encuentraprecios",
        "label":"Encuentraprecios",
        "country":"ES"
    },
    {
        "key":"pricesavvy",
        "label":"Pricesavvy",
        "country":"GB"
    },
    {
        "key":"emag",
        "label":"Emag",
        "country":"PL"
    },
    {
        "key":"adcell",
        "label":"Adcell",
        "country":"DE"
    },
    {
        "key":"legrandshop",
        "label":"Le Grand Shop",
        "country":"FR"
    },
    {
        "key":"moebel24",
        "label":"Moebel24",
        "country":"DE"
    },
    {
        "key":"domodi",
        "label":"Domodi",
        "country":"DE"
    },
    {
        "key":"fruugo",
        "label":"Fruugo",
        "country":"DE"
    },
    {
        "key":"tweakwise_v2",
        "label":"Tweakwise",
        "country":"NL"
    },
    {
        "key":"adcrowd",
        "label":"Adcrowd",
        "country":"NL"
    },
    {
        "key":"google_dynamic_display_ads",
        "label":"Google Dynamic Display Ads",
        "country":"AT"
    },
    {
        "key":"stadnl",
        "label":"StadNl",
        "country":"NL"
    },
    {
        "key":"mercamania",
        "label":"Mercamania",
        "country":"ES"
    },
    {
        "key":"clubic",
        "label":"Clubic",
        "country":"FR"
    },
    {
        "key":"shop_online_shop",
        "label":"Shop-Online-Shop",
        "country":"NL"
    },
    {
        "key":"fashionchick",
        "label":"Fashionchick",
        "country":"DE"
    },
    {
        "key":"preissuchmaschine",
        "label":"Preissuchmaschine",
        "country":"DE"
    },
    {
        "key":"fyndiq",
        "label":"Fyndiq",
        "country":"SE"
    },
    {
        "key":"bloomville",
        "label":"Bloomville",
        "country":"NL"
    },
    {
        "key":"bigshopper",
        "label":"Bigshopper",
        "country":"AT"
    },
    {
        "key":"compartner",
        "label":"Compartner",
        "country":"NL"
    },
    {
        "key":"hood",
        "label":"Hood",
        "country":"DE"
    },
    {
        "key":"medifusion",
        "label":"Medifusion",
        "country":"GB"
    },
    {
        "key":"supersales",
        "label":"SuperSales",
        "country":"BE"
    },
    {
        "key":"custom_txt",
        "label":"Custom (TXT)",
        "country":"RS"
    },
    {
        "key":"pagomeno",
        "label":"Pagemeno",
        "country":"IT"
    },
    {
        "key":"koopkeus",
        "label":"KoopKeus",
        "country":"NL"
    },
    {
        "key":"hatch",
        "label":"Hatch",
        "country":"AT"
    },
    {
        "key":"bazaarvoice",
        "label":"Bazaarvoice",
        "country":"NL"
    },
    {
        "key":"miintotsv",
        "label":"Miinto (TSV)",
        "country":"DE"
    },
    {
        "key":"pricat_fashion",
        "label":"Pricat FashionUnited",
        "country":"NL"
    },
    {
        "key":"medvergleich",
        "label":"Medvergleich",
        "country":"DE"
    },
    {
        "key":"indeed",
        "label":"Indeed",
        "country":"BE"
    },
    {
        "key":"sparmedo",
        "label":"Sparmedo",
        "country":"DE"
    },
    {
        "key":"tobedressed",
        "label":"To Be Dressed",
        "country":"NL"
    },
    {
        "key":"shoppingdach",
        "label":"Shopping",
        "country":"AT"
    },
    {
        "key":"mybestbrands",
        "label":"Mybestbrands",
        "country":"DE"
    },
    {
        "key":"preis",
        "label":"Preis",
        "country":"DE"
    },
    {
        "key":"daisycon",
        "label":"Daisycon",
        "country":"BE"
    },
    {
        "key":"clang",
        "label":"Clang",
        "country":"BE"
    },
    {
        "key":"custom_json",
        "label":"Custom (JSON)",
        "country":"RS"
    },
    {
        "key":"kiyoh",
        "label":"Kiyoh",
        "country":"NL"
    },
    {
        "key":"stileo",
        "label":"Stileo",
        "country":"ES"
    },
    {
        "key":"uzerly",
        "label":"Uzerly",
        "country":"FR"
    },
    {
        "key":"cezigue",
        "label":"Cezigue",
        "country":"FR"
    },
    {
        "key":"hertie",
        "label":"Hertie",
        "country":"DE"
    },
    {
        "key":"winesearcher",
        "label":"Winesearcher",
        "country":"GB"
    },
    {
        "key":"ciao",
        "label":"Ciao",
        "country":"SE"
    },
    {
        "key":"spotta",
        "label":"Spotta",
        "country":"NL"
    },
    {
        "key":"custom_unescaped",
        "label":"Custom XML (Unescaped)",
        "country":"RS"
    },
    {
        "key":"kieskeurig",
        "label":"Kieskeurig",
        "country":"BE"
    },
    {
        "key":"cherchons",
        "label":"Cherchons",
        "country":"FR"
    },
    {
        "key":"snapchat",
        "label":"Snapchat",
        "country":"AE"
    },
    {
        "key":"shopmania",
        "label":"Shopmania",
        "country":"AR"
    },
    {
        "key":"sizmek",
        "label":"Sizmek",
        "country":"DE"
    },
    {
        "key":"yandex",
        "label":"Yandex",
        "country":"KZ"
    },
    {
        "key":"storesquare",
        "label":"Storesquare",
        "country":"BE"
    },
    {
        "key":"outdoordeals",
        "label":"OutdoorDeals",
        "country":"DE"
    },
    {
        "key":"doofinder",
        "label":"Doofinder",
        "country":"ES"
    },
    {
        "key":"zalando",
        "label":"Zalando",
        "country":"DE"
    },
    {
        "key":"affilinet",
        "label":"Affilinet",
        "country":"DE"
    },
    {
        "key":"shopr",
        "label":"Shopr",
        "country":"NL"
    },
    {
        "key":"beslist",
        "label":"Beslist",
        "country":"BE"
    },
    {
        "key":"kauftipp",
        "label":"Kauftipp",
        "country":"CH"
    },
    {
        "key":"twenga_v2",
        "label":"Twenga",
        "country":"US"
    },
    {
        "key":"testit",
        "label":"Testit",
        "country":"DE"
    },
    {
        "key":"ceneo",
        "label":"Ceneo",
        "country":"PL"
    },
    {
        "key":"kuantokusta",
        "label":"KuantoKusta",
        "country":"PT"
    },
    {
        "key":"getprice",
        "label":"Getprice",
        "country":"AT"
    },
    {
        "key":"vendiro",
        "label":"Vendiro",
        "country":"DE"
    },
    {
        "key":"prisync",
        "label":"Prisync",
        "country":"AE"
    },
    {
        "key":"livingo",
        "label":"Livingo",
        "country":"DE"
    },
    {
        "key":"viatvwonen",
        "label":"viavtwonen",
        "country":"NL"
    },
    {
        "key":"moebel",
        "label":"Meubles",
        "country":"FR"
    },
    {
        "key":"whiskymarketplace",
        "label":"Whiskymarketplace",
        "country":"GB"
    },
    {
        "key":"nextag",
        "label":"Nextag",
        "country":"AU"
    },
    {
        "key":"runbabyrun",
        "label":"Run Baby Run",
        "country":"FR"
    },
    {
        "key":"tradedoubler",
        "label":"Tradedoubler",
        "country":"AT"
    },
    {
        "key":"sociomantic",
        "label":"Sociomantic",
        "country":"DE"
    },
    {
        "key":"ricardo",
        "label":"Ricardo",
        "country":"CH"
    },
    {
        "key":"adform",
        "label":"Adform",
        "country":"NL"
    },
    {
        "key":"netzshopping",
        "label":"Netzshopping",
        "country":"DE"
    },
    {
        "key":"check24",
        "label":"Check24",
        "country":"DE"
    },
    {
        "key":"googleproductreview",
        "label":"Google Product Review",
        "country":"CH"
    },
    {
        "key":"nokaut",
        "label":"Nokaut",
        "country":"PL"
    },
    {
        "key":"vergelijk_v2",
        "label":"Vergelijk",
        "country":"NL"
    },
    {
        "key":"medizinfuchs",
        "label":"Medizinfuchs",
        "country":"DE"
    },
    {
        "key":"commerce_connector_v2",
        "label":"Commerce Connector",
        "country":"DE"
    },
    {
        "key":"listupp",
        "label":"Listupp",
        "country":"BR"
    },
    {
        "key":"stockbase",
        "label":"Stockbase",
        "country":"NL"
    },
    {
        "key":"preisroboter",
        "label":"PreisRoboter",
        "country":"DE"
    },
    {
        "key":"winkelstraat",
        "label":"Winkelstraat.nl",
        "country":"NL"
    },
    {
        "key":"stylelounge",
        "label":"Stylelounge",
        "country":"CH"
    },
    {
        "key":"bipp",
        "label":"BIPP",
        "country":"NL"
    },
    {
        "key":"cj",
        "label":"CJ",
        "country":"AT"
    },
    {
        "key":"restposten",
        "label":"Restposten",
        "country":"DE"
    },
    {
        "key":"rueducommerce",
        "label":"Rue du Commerce",
        "country":"FR"
    },
    {
        "key":"amazon",
        "label":"Amazon",
        "country":"DE"
    },
    {
        "key":"power_reviews",
        "label":"Power Reviews",
        "country":"DE"
    },
    {
        "key":"tracdelight",
        "label":"Tracdelight",
        "country":"DE"
    },
    {
        "key":"epoq",
        "label":"epoq",
        "country":"DE"
    },
    {
        "key":"producthero",
        "label":"Producthero",
        "country":"AT"
    },
    {
        "key":"stylight",
        "label":"Stylight",
        "country":"AT"
    },
    {
        "key":"admitad",
        "label":"Admitad",
        "country":"ES"
    },
    {
        "key":"wundercurves",
        "label":"Wundercurves",
        "country":"DE"
    },
    {
        "key":"trovit",
        "label":"Trovit",
        "country":"AR"
    },
    {
        "key":"bijons_amsterdam",
        "label":"Bij Ons Amsterdam",
        "country":"NL"
    },
    {
        "key":"idealo",
        "label":"Idealo",
        "country":"AT"
    },
    {
        "key":"myshopping",
        "label":"Myshopping",
        "country":"AU"
    },
    {
        "key":"olx",
        "label":"OLX",
        "country":"BR"
    },
    {
        "key":"shopalike",
        "label":"Shopalike",
        "country":"BE"
    },
    {
        "key":"shopwelt",
        "label":"Shopwelt",
        "country":"DE"
    },
    {
        "key":"pinterest",
        "label":"Pinterest",
        "country":"BR"
    },
    {
        "key":"siroop",
        "label":"Siroop",
        "country":"CH"
    },
    {
        "key":"beaute_test",
        "label":"Beauté Test",
        "country":"FR"
    },
    {
        "key":"moebel",
        "label":"Moebel",
        "country":"DE"
    },
    {
        "key":"billiger_new",
        "label":"Billiger",
        "country":"DE"
    },
    {
        "key":"belboon",
        "label":"Belboon",
        "country":"DE"
    },
    {
        "key":"search_ads_360",
        "label":"Search Ads 360",
        "country":"AT"
    },
    {
        "key":"connexity",
        "label":"Connexity",
        "country":"DE"
    },
    {
        "key":"biano",
        "label":"Biano",
        "country":"NL"
    },
    {
        "key":"heureka",
        "label":"Heureka",
        "country":"CZ"
    },
    {
        "key":"voordeelgroep",
        "label":"Voordeelgroep",
        "country":"NL"
    },
    {
        "key":"meinpaket",
        "label":"Allyouneed",
        "country":"DE"
    },
    {
        "key":"shopzilla",
        "label":"Shopzilla",
        "country":"DE"
    },
    {
        "key":"zap",
        "label":"Zap",
        "country":"BR"
    },
    {
        "key":"ledenicheur",
        "label":"Le Dénicheur",
        "country":"FR"
    },
    {
        "key":"instagram",
        "label":"Instagram (by Facebook)",
        "country":"AT"
    },
    {
        "key":"affiliatewindow",
        "label":"AffiliateWindow",
        "country":"NL"
    },
    {
        "key":"kelkoo",
        "label":"Kelkoo",
        "country":"AT"
    },
    {
        "key":"emarts",
        "label":"Emarts",
        "country":"NL"
    },
    {
        "key":"Okazii",
        "label":"Okazii Europe",
        "country":"RO"
    },
    {
        "key":"hardwareinfo",
        "label":"Hardware.info",
        "country":"BE"
    },
    {
        "key":"rakuten",
        "label":"Rakuten France",
        "country":"DE"
    },
    {
        "key":"fashiola",
        "label":"Fashiola",
        "country":"AT"
    },
    {
        "key":"kwanko",
        "label":"Kwanko",
        "country":"DE"
    },
    {
        "key":"vertaa_v2",
        "label":"Vertaa",
        "country":"GB"
    },
    {
        "key":"wepublish",
        "label":"Wepublish",
        "country":"BE"
    },
    {
        "key":"commissionjunction",
        "label":"Commission Junction",
        "country":"DE"
    },
    {
        "key":"webmarchand",
        "label":"Webmarchand",
        "country":"LU"
    },
    {
        "key":"custom_rss",
        "label":"Custom RSS",
        "country":"RS"
    },
    {
        "key":"dooyoo",
        "label":"Dooyoo",
        "country":"BE"
    },
    {
        "key":"become",
        "label":"Become Europe",
        "country":"DE"
    },
    {
        "key":"facebook",
        "label":"Facebook",
        "country":"AT"
    },
    {
        "key":"apomio",
        "label":"Apomio",
        "country":"DE"
    },
    {
        "key":"shopsuite",
        "label":"Shopsuite",
        "country":"AE"
    },
    {
        "key":"google_dynamic_search_ads",
        "label":"Google Dynamic Search Ads",
        "country":"AT"
    },
    {
        "key":"fnac",
        "label":"Fnac",
        "country":"FR"
    },
    {
        "key":"joblift",
        "label":"Joblift",
        "country":"DE"
    },
    {
        "key":"tradetracker",
        "label":"TradeTracker",
        "country":"AT"
    },
    {
        "key":"wish",
        "label":"Wish",
        "country":"BE"
    },
    {
        "key":"preisvergleich",
        "label":"Preisvergleich",
        "country":"AT"
    },
    {
        "key":"hintaopas",
        "label":"Hintaopas",
        "country":"FI"
    },
    {
        "key":"adroll",
        "label":"AdRoll",
        "country":"DE"
    },
    {
        "key":"prisvis",
        "label":"Prisvis",
        "country":"SE"
    },
    {
        "key":"converto",
        "label":"Converto",
        "country":"CH"
    },
    {
        "key":"pureshopping",
        "label":"Pure Shopping",
        "country":"FR"
    },
    {
        "key":"coolshop",
        "label":"Coolshop",
        "country":"DE"
    },
    {
        "key":"monetate",
        "label":"Monetate",
        "country":"BE"
    },
    {
        "key":"lionshome",
        "label":"LionsHome",
        "country":"AT"
    },
    {
        "key":"galaxus_v2",
        "label":"Galaxus",
        "country":"CH"
    },
    {
        "key":"frendz",
        "label":"Frendz",
        "country":"NL"
    },
    {
        "key":"ooshopping",
        "label":"OOShopping",
        "country":"NL"
    },
    {
        "key":"hometiger",
        "label":"HomeTiger",
        "country":"FR"
    },
    {
        "key":"stylefruits",
        "label":"Stylefruits",
        "country":"DE"
    },
    {
        "key":"webkubiec",
        "label":"Webkubiec",
        "country":"PL"
    },
    {
        "key":"choozen",
        "label":"Choozen",
        "country":"AT"
    },
    {
        "key":"shoparize",
        "label":"Shoparize",
        "country":"PL"
    },
    {
        "key":"vindkleding",
        "label":"Vind-Kleding",
        "country":"NL"
    },
    {
        "key":"handys",
        "label":"Handys",
        "country":"DE"
    },
    {
        "key":"homedeco",
        "label":"HomeDeco",
        "country":"NL"
    },
    {
        "key":"sellvation",
        "label":"Sellvation",
        "country":"NL"
    },
    {
        "key":"xing",
        "label":"XING",
        "country":"DE"
    },
    {
        "key":"datatrics",
        "label":"Datatrics",
        "country":"NL"
    },
    {
        "key":"awin_csv",
        "label":"Awin (CSV)",
        "country":"NL"
    },
    {
        "key":"geizkragen",
        "label":"Geizkragen",
        "country":"DE"
    },
    {
        "key":"yippie",
        "label":"Yippie!",
        "country":"NL"
    },
    {
        "key":"cenowarka",
        "label":"Cenowarka",
        "country":"PL"
    },
    {
        "key":"modile",
        "label":"Modile",
        "country":"PL"
    },
    {
        "key":"winkeleninnederland",
        "label":"Winkelen in Nederland",
        "country":"NL"
    },
    {
        "key":"polyvore",
        "label":"Polyvore",
        "country":"AU"
    },
    {
        "key":"thirtyonem2",
        "label":"31m2",
        "country":"FR"
    },
    {
        "key":"mitula",
        "label":"Mitula",
        "country":"MX"
    },
    {
        "key":"viafix",
        "label":"Viafix",
        "country":"NL"
    },
    {
        "key":"comparer",
        "label":"Comparer",
        "country":"BE"
    },
    {
        "key":"touslesprix",
        "label":"Touslesprix",
        "country":"FR"
    },
    {
        "key":"shopping24",
        "label":"Shopping24",
        "country":"DE"
    },
    {
        "key":"priceminister",
        "label":"Priceminister",
        "country":"FR"
    },
    {
        "key":"okazje",
        "label":"Okazje",
        "country":"PL"
    },
    {
        "key":"zbozi",
        "label":"Zbozi",
        "country":"CZ"
    },
    {
        "key":"adtraction",
        "label":"Adtraction",
        "country":"DE"
    },
    {
        "key":"geizhals",
        "label":"Geizhals",
        "country":"AT"
    },
    {
        "key":"webgains",
        "label":"Webgains",
        "country":"AU"
    },
    {
        "key":"google_manufacturer_center",
        "label":"Google Manufacturer Center",
        "country":"AR"
    },
    {
        "key":"glami",
        "label":"Glami",
        "country":"BE"
    },
    {
        "key":"mercateo",
        "label":"Mercateo",
        "country":"DE"
    },
    {
        "key":"crowdfox",
        "label":"Crowdfox",
        "country":"DE"
    },
    {
        "key":"drezzy",
        "label":"Drezzy",
        "country":"ES"
    },
    {
        "key":"kleding_nl",
        "label":"Kleding.nl",
        "country":"NL"
    },
    {
        "key":"criteo",
        "label":"Criteo",
        "country":"AT"
    },
    {
        "key":"real_content",
        "label":"Real Content",
        "country":"DE"
    },
    {
        "key":"shopdichtbij",
        "label":"Shopdichtbij",
        "country":"NL"
    },
    {
        "key":"manomano",
        "label":"ManoMano",
        "country":"DE"
    },
    {
        "key":"promodeal",
        "label":"Promodeal",
        "country":"NL"
    },
    {
        "key":"jobboard",
        "label":"JobBoard.io",
        "country":"DE"
    },
    {
        "key":"giftboxx",
        "label":"Giftboxx",
        "country":"NL"
    },
    {
        "key":"googleshopping",
        "label":"Google Shopping",
        "country":"AE"
    },
    {
        "key":"privalia",
        "label":"Privalia",
        "country":"ES"
    },
    {
        "key":"incurvy",
        "label":"Incurvy",
        "country":"DE"
    },
    {
        "key":"ladenzeile",
        "label":"Ladenzeile",
        "country":"AT"
    },
    {
        "key":"pricespy",
        "label":"PriceSpy",
        "country":"GB"
    },
    {
        "key":"outtra",
        "label":"Outtra",
        "country":"DE"
    },
    {
        "key":"trovaprezzi",
        "label":"Trovaprezzi",
        "country":"IT"
    },
    {
        "key":"deltaprojects",
        "label":"Deltaprojects",
        "country":"NL"
    },
    {
        "key":"scoupz",
        "label":"Scoupz",
        "country":"NL"
    },
    {
        "key":"hintaseuranta",
        "label":"Hintaseuranta",
        "country":"FI"
    },
    {
        "key":"prisjakt",
        "label":"Prisjakt",
        "country":"SE"
    },
    {
        "key":"bing",
        "label":"Bing ads",
        "country":"AU"
    },
    {
        "key":"publitas",
        "label":"Publitas",
        "country":"NL"
    },
    {
        "key":"prijsvergelijk",
        "label":"Prijsvergelijk",
        "country":"NL"
    },
    {
        "key":"pricegrabber",
        "label":"Pricegrabber",
        "country":"GB"
    },
    {
        "key":"skapiec",
        "label":"Skapiec",
        "country":"PL"
    },
    {
        "key":"uvinum",
        "label":"Uvinum",
        "country":"FR"
    },
    {
        "key":"satisfiedshopping",
        "label":"Satisfied Shopping",
        "country":"NL"
    },
    {
        "key":"meetrix",
        "label":"Lootjestrekken",
        "country":"NL"
    },
    {
        "key":"boetieknl",
        "label":"Boetiek.nl",
        "country":"NL"
    },
    {
        "key":"tweakers",
        "label":"Tweakers",
        "country":"BE"
    },
    {
        "key":"prezzostop",
        "label":"Prezzostop",
        "country":"IT"
    },
    {
        "key":"rtb_house",
        "label":"RTB House",
        "country":"BR"
    },
    {
        "key":"everysize",
        "label":"Everysize",
        "country":"DE"
    },
    {
        "key":"lesbonnesbouilles",
        "label":"Les Bonnes Bouilles",
        "country":"FR"
    },
    {
        "key":"shopello",
        "label":"Shopello",
        "country":"DK"
    },
    {
        "key":"seetheworld",
        "label":"SeeTheWorld",
        "country":"GB"
    },
    {
        "key":"lyst",
        "label":"Lyst",
        "country":"FR"
    },
    {
        "key":"adzuna",
        "label":"Adzuna",
        "country":"DE"
    },
    {
        "key":"teilehaber",
        "label":"TEILeHABER.de",
        "country":"DE"
    },
    {
        "key":"vivino",
        "label":"Vivino",
        "country":"DE"
    },
    {
        "key":"locamo",
        "label":"Locamo",
        "country":"DE"
    },
    {
        "key":"pagineprezzi",
        "label":"Pagineprezzi",
        "country":"IT"
    },
    {
        "key":"kompario",
        "label":"Kompario",
        "country":"PL"
    },
    {
        "key":"spartoo_v2",
        "label":"Spartoo",
        "country":"BE"
    },
    {
        "key":"leguide",
        "label":"LeGuide",
        "country":"BE"
    },
    {
        "key":"trendsales",
        "label":"Trendsales",
        "country":"DK"
    },
    {
        "key":"adps",
        "label":"ADPS",
        "country":"NL"
    },
    {
        "key":"kiesproduct",
        "label":"Kiesproduct",
        "country":"NL"
    },
    {
        "key":"logicsale",
        "label":"Logicsale",
        "country":"NL"
    },
    {
        "key":"shopwahl",
        "label":"Shopwahl",
        "country":"DE"
    },
    {
        "key":"shoppydoo",
        "label":"Shoppydoo",
        "country":"ES"
    },
    {
        "key":"fasha",
        "label":"Fasha",
        "country":"NL"
    },
    {
        "key":"hitmeister",
        "label":"Hitmeister",
        "country":"DE"
    },
    {
        "key":"bol",
        "label":"Bol.com",
        "country":"NL"
    },
    {
        "key":"bikeexchange",
        "label":"Bike Exchange",
        "country":"DE"
    },
    {
        "key":"thenextad",
        "label":"TheNextAd",
        "country":"DE"
    },
    {
        "key":"timeone",
        "label":"TimeOne",
        "country":"FR"
    },
    {
        "key":"skinflint",
        "label":"Skinflint",
        "country":"GB"
    },
    {
        "key":"custom",
        "label":"Custom XML",
        "country":"RS"
    },
    {
        "key":"smartly",
        "label":"Smartly",
        "country":"CH"
    },
    {
        "key":"allani",
        "label":"Allani",
        "country":"PL"
    },
    {
        "key":"pricerunner",
        "label":"PriceRunner",
        "country":"AT"
    },
    {
        "key":"gobanana",
        "label":"Go-Banana",
        "country":"GB"
    },
    {
        "key":"sooqr_v2",
        "label":"Sooqr",
        "country":"NL"
    },
    {
        "key":"guenstiger",
        "label":"Guenstiger",
        "country":"DE"
    },
    {
        "key":"promobutler",
        "label":"Promobutler",
        "country":"BE"
    }
];

export default channelList;